FROM postgres:13
# ENV PG_VERSION 13

# COPY config/postgresql.conf /tmp/postgresql.conf
# COPY initdb/runConfig.sh /docker-entrypoint-initdb.d/runConfig.sh
# RUN mv /docker-entrypoint-initdb.d/postgresql.conf /data/postgres/

# ADD initdb/init-db-sample.sql /docker-entrypoint-initdb.d/


